import { PageDocument, usePageQuery } from "../generated/graphql";
import { client, ssrCache } from "../lib/urql";

import { GetServerSideProps } from "next";
import Head from "next/head";

export default function Home() {
  const [{ data }] = usePageQuery({ variables: { slug: "home" } });
  console.log("🚀 ~ file: index.tsx:11 ~ Home ~ data", data);
  return (
    <div>
      <Head>
        <title>project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{data?.page?.title}</h1>
      <span>{data?.page?.subtitle}</span>
      <h3>asdf</h3>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  await client.query(PageDocument, { slug: "home" }).toPromise();

  return {
    props: {
      urqlState: ssrCache.extractData(),
    },
  };
};
